version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 rm s3://thomasmcleary.com --recursive
artifacts:
  base-directory: build
  files:
    - '**/*'
cache:
  paths:
    - 'node_modules/**/*'